"""
Generate BasicMath Form 2 2023 NECTA Answer Key PDF
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import cm, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
import os

DARK_BLUE = HexColor("#1a5276")
GREEN = HexColor("#27ae60")
LIGHT_BLUE_BG = HexColor("#e8eaf6")
WARNING_BG = HexColor("#fff3e0")
WARNING_BORDER = HexColor("#ff9800")
TIP_BG = HexColor("#e3f2fd")
TIP_BORDER = HexColor("#1976d2")
ANSWER_BG = HexColor("#f1f8e9")
BORDER_GRAY = HexColor("#e0e0e0")
SECTION_BG = HexColor("#ede7f6")

WIDTH, HEIGHT = A4
OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "BasicMath-F2-2023 (Answer Key).pdf")


def build_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle('CoverTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=42, textColor=DARK_BLUE, alignment=TA_CENTER, spaceAfter=6))
    styles.add(ParagraphStyle('CoverSubtitle', parent=styles['Normal'], fontName='Helvetica', fontSize=14, textColor=HexColor("#555555"), alignment=TA_CENTER, spaceAfter=10))
    styles.add(ParagraphStyle('CoverTagline', parent=styles['Normal'], fontName='Helvetica', fontSize=12, textColor=HexColor("#555555"), alignment=TA_CENTER, spaceAfter=10))
    styles.add(ParagraphStyle('CoverURL', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=18, textColor=GREEN, alignment=TA_CENTER))
    styles.add(ParagraphStyle('CoverShare', parent=styles['Normal'], fontName='Helvetica-Oblique', fontSize=11, textColor=HexColor("#666666"), alignment=TA_CENTER, spaceAfter=6))
    styles.add(ParagraphStyle('CoverFooter', parent=styles['Normal'], fontName='Helvetica', fontSize=9, textColor=HexColor("#999999"), alignment=TA_CENTER))
    styles.add(ParagraphStyle('TitlePageHeading', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=28, textColor=DARK_BLUE, alignment=TA_CENTER, spaceAfter=10))
    styles.add(ParagraphStyle('TitlePageSub', parent=styles['Normal'], fontName='Helvetica', fontSize=16, textColor=HexColor("#333333"), alignment=TA_CENTER, spaceAfter=6))
    styles.add(ParagraphStyle('QuestionHeading', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=16, textColor=white, alignment=TA_LEFT, spaceAfter=6, spaceBefore=12))
    styles.add(ParagraphStyle('SubPart', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=12, textColor=DARK_BLUE, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle('BodyText2', parent=styles['Normal'], fontName='Helvetica', fontSize=11, textColor=HexColor("#222222"), leading=16, spaceAfter=4))
    styles.add(ParagraphStyle('StepText', parent=styles['Normal'], fontName='Helvetica', fontSize=11, textColor=HexColor("#333333"), leading=16, spaceAfter=2, leftIndent=15))
    styles.add(ParagraphStyle('ClosingTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=30, textColor=DARK_BLUE, alignment=TA_CENTER, spaceAfter=10))
    styles.add(ParagraphStyle('ClosingText', parent=styles['Normal'], fontName='Helvetica', fontSize=14, textColor=HexColor("#333333"), alignment=TA_CENTER, leading=20, spaceAfter=8))
    return styles


def footer_func(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(HexColor("#666666"))
    canvas.drawCentredString(WIDTH / 2, 15 * mm, "mytzstudies.com | Free Tanzanian Exam Resources")
    canvas.restoreState()


def qheader(num, title, styles):
    data = [[Paragraph(f"Question {num}: {title}", styles['QuestionHeading'])]]
    t = Table(data, colWidths=[WIDTH - 80])
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, -1), DARK_BLUE), ('TOPPADDING', (0, 0), (-1, -1), 8), ('BOTTOMPADDING', (0, 0), (-1, -1), 8), ('LEFTPADDING', (0, 0), (-1, -1), 12), ('RIGHTPADDING', (0, 0), (-1, -1), 12)]))
    return t


def _box(title, text, bg, border, tc, bc):
    c = [[Paragraph(f"<b>{title}</b>", ParagraphStyle('BH', fontName='Helvetica-Bold', fontSize=11, textColor=tc, spaceAfter=3))], [Paragraph(text, ParagraphStyle('BB', fontName='Helvetica', fontSize=10, textColor=bc, leading=14))]]
    t = Table(c, colWidths=[WIDTH - 100])
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, -1), bg), ('BOX', (0, 0), (-1, -1), 1.5, border), ('TOPPADDING', (0, 0), (-1, -1), 6), ('BOTTOMPADDING', (0, 0), (-1, -1), 6), ('LEFTPADDING', (0, 0), (-1, -1), 10), ('RIGHTPADDING', (0, 0), (-1, -1), 10)]))
    return t


def warn(text): return _box("Common Mistake Warning", text, WARNING_BG, WARNING_BORDER, HexColor("#e65100"), HexColor("#bf360c"))
def tip(text): return _box("Study Tip", text, TIP_BG, TIP_BORDER, HexColor("#0d47a1"), HexColor("#1565c0"))


def ans(text):
    c = [[Paragraph(text, ParagraphStyle('AI', fontName='Helvetica-Bold', fontSize=12, textColor=HexColor("#1b5e20"), leading=16))]]
    t = Table(c, colWidths=[WIDTH - 100])
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, -1), ANSWER_BG), ('BOX', (0, 0), (-1, -1), 1, GREEN), ('TOPPADDING', (0, 0), (-1, -1), 6), ('BOTTOMPADDING', (0, 0), (-1, -1), 6), ('LEFTPADDING', (0, 0), (-1, -1), 10), ('RIGHTPADDING', (0, 0), (-1, -1), 10)]))
    return t


def summary(text):
    c = [[Paragraph(f"<b>Section Summary:</b> {text}", ParagraphStyle('SI', fontName='Helvetica', fontSize=11, textColor=HexColor("#4a148c"), leading=15))]]
    t = Table(c, colWidths=[WIDTH - 100])
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, -1), SECTION_BG), ('BOX', (0, 0), (-1, -1), 1, HexColor("#7e57c2")), ('TOPPADDING', (0, 0), (-1, -1), 6), ('BOTTOMPADDING', (0, 0), (-1, -1), 6), ('LEFTPADDING', (0, 0), (-1, -1), 10), ('RIGHTPADDING', (0, 0), (-1, -1), 10)]))
    return t


def build_pdf():
    styles = build_styles()
    doc = SimpleDocTemplate(OUTPUT_PATH, pagesize=A4, topMargin=25*mm, bottomMargin=25*mm, leftMargin=20*mm, rightMargin=20*mm)
    story = []
    S = lambda pts: Spacer(1, pts)
    body = styles['BodyText2']
    st = styles['StepText']
    sub = styles['SubPart']

    # ========== COVER ==========
    story.append(S(60))
    story.append(Paragraph("myTZStudies", styles['CoverTitle']))
    story.append(S(4))
    story.append(Paragraph("Your Free Tanzanian Exam Library", styles['CoverSubtitle']))
    story.append(S(10))
    story.append(HRFlowable(width="80%", thickness=2, color=DARK_BLUE, spaceAfter=10, spaceBefore=5))
    story.append(S(6))
    story.append(Paragraph("Past papers, answer keys, and study resources for Tanzanian students.", styles['CoverTagline']))
    story.append(S(10))
    story.append(Paragraph("mytzstudies.com", styles['CoverURL']))
    story.append(S(30))
    fs = ParagraphStyle('FI', fontName='Helvetica-Bold', fontSize=11, textColor=DARK_BLUE, alignment=TA_CENTER)
    feats = ["Past Exam Papers", "Answer Keys", "Free Access", "Standard 4 to Form 6", "All Subjects Covered", "Updated Regularly"]
    cw = (WIDTH - 80) / 3
    ft = Table([[Paragraph(f, fs) for f in feats[:3]], [Paragraph(f, fs) for f in feats[3:]]], colWidths=[cw]*3, rowHeights=[45, 45])
    ft.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, -1), LIGHT_BLUE_BG), ('BOX', (0, 0), (0, 0), 1, BORDER_GRAY), ('BOX', (1, 0), (1, 0), 1, BORDER_GRAY), ('BOX', (2, 0), (2, 0), 1, BORDER_GRAY), ('BOX', (0, 1), (0, 1), 1, BORDER_GRAY), ('BOX', (1, 1), (1, 1), 1, BORDER_GRAY), ('BOX', (2, 1), (2, 1), 1, BORDER_GRAY), ('ALIGN', (0, 0), (-1, -1), 'CENTER'), ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'), ('TOPPADDING', (0, 0), (-1, -1), 10), ('BOTTOMPADDING', (0, 0), (-1, -1), 10)]))
    story.append(ft)
    story.append(S(40))
    story.append(Paragraph("Share this with a friend. Every student deserves free study materials.", styles['CoverShare']))
    story.append(S(10))
    story.append(HRFlowable(width="60%", thickness=0.5, color=BORDER_GRAY, spaceAfter=10))
    story.append(Paragraph("Made with mytzstudies.com", styles['CoverFooter']))
    story.append(PageBreak())

    # ========== TITLE ==========
    story.append(S(100))
    story.append(Paragraph("BASIC MATHEMATICS - FORM TWO", styles['TitlePageHeading']))
    story.append(S(10))
    story.append(Paragraph("National Assessment 2023 - Answer Key", styles['TitlePageSub']))
    story.append(S(20))
    info = [["Subject", "Basic Mathematics"], ["Code", "041"], ["Level", "Form Two"], ["Year", "2023"], ["Exam Board", "NECTA"], ["Type", "Answer Key"], ["Total Questions", "10 (10 marks each)"]]
    it = Table(info, colWidths=[150, 250])
    it.setStyle(TableStyle([('BACKGROUND', (0, 0), (0, -1), LIGHT_BLUE_BG), ('TEXTCOLOR', (0, 0), (0, -1), DARK_BLUE), ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'), ('FONTNAME', (1, 0), (1, -1), 'Helvetica'), ('FONTSIZE', (0, 0), (-1, -1), 12), ('GRID', (0, 0), (-1, -1), 0.5, BORDER_GRAY), ('TOPPADDING', (0, 0), (-1, -1), 6), ('BOTTOMPADDING', (0, 0), (-1, -1), 6), ('LEFTPADDING', (0, 0), (-1, -1), 10)]))
    story.append(it)
    story.append(PageBreak())

    # ===== Q1: Multiples and Decimals =====
    story.append(qheader(1, "Multiples and Decimal Operations", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) List the first twelve multiples of 4 and 5 and identify the common multiples.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("A multiple is what you get when you multiply a number by 1, 2, 3, 4, and so on.", body))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> List the first 12 multiples of 4:", st))
    story.append(Paragraph("4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> List the first 12 multiples of 5:", st))
    story.append(Paragraph("5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Find numbers that appear in BOTH lists:", st))
    story.append(Paragraph("20 appears in both lists (4 x 5 = 20 and 5 x 4 = 20)", st))
    story.append(Paragraph("40 appears in both lists (4 x 10 = 40 and 5 x 8 = 40)", st))
    story.append(S(4))
    story.append(ans("Final Answer: Common multiples are 20 and 40"))
    story.append(S(6))
    story.append(tip("The smallest common multiple is called the LCM (Lowest Common Multiple). Here, LCM of 4 and 5 = 20. All common multiples are multiples of the LCM."))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Evaluate (2/25) x 0.737 correct to:</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> First, convert 2/25 to a decimal:", st))
    story.append(Paragraph("2/25 = 2 divided by 25 = 0.08", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Multiply: 0.08 x 0.737 = 0.05896", st))
    story.append(S(4))
    story.append(Paragraph("<b>(i) To one significant figure:</b>", sub))
    story.append(Paragraph("0.05896 - the first significant figure is 5 (we skip the leading zeros and the 0). Looking at the next digit (8), since 8 is 5 or more, round up.", st))
    story.append(ans("Answer: 0.06"))
    story.append(S(4))
    story.append(Paragraph("<b>(ii) To three decimal places:</b>", sub))
    story.append(Paragraph("0.05896 - look at 3 digits after decimal: 058. The next digit is 9, so round up the 8.", st))
    story.append(ans("Answer: 0.059"))
    story.append(S(6))
    story.append(warn("Significant figures and decimal places are different! In 0.05896: there are 4 significant figures (5, 8, 9, 6) but the zeros before 5 are NOT significant - they are just placeholders."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Multiples, LCM, decimal multiplication, significant figures, decimal places. Study tip: Leading zeros are never significant."))
    story.append(PageBreak())

    # ===== Q2: Fractions and Percentages =====
    story.append(qheader(2, "Fractions and Percentage Increase", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) Arrange 2/3, 4/7, 3/8, and 5/9 in ascending order (smallest to largest).</b>", sub))
    story.append(S(4))
    story.append(Paragraph("To compare fractions, we need to give them all the same bottom number (denominator).", body))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Find the LCD (Lowest Common Denominator) of 3, 7, 8, and 9.", st))
    story.append(Paragraph("LCD = 504", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Convert each fraction:", st))
    story.append(Paragraph("2/3 = (2 x 168)/(3 x 168) = 336/504", st))
    story.append(Paragraph("4/7 = (4 x 72)/(7 x 72) = 288/504", st))
    story.append(Paragraph("3/8 = (3 x 63)/(8 x 63) = 189/504", st))
    story.append(Paragraph("5/9 = (5 x 56)/(9 x 56) = 280/504", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Now compare the top numbers (numerators):", st))
    story.append(Paragraph("189 &lt; 280 &lt; 288 &lt; 336", st))
    story.append(Paragraph("So: 3/8 &lt; 5/9 &lt; 4/7 &lt; 2/3", st))
    story.append(S(4))
    story.append(ans("Final Answer: 3/8, 5/9, 4/7, 2/3 (ascending order)"))
    story.append(S(8))

    story.append(Paragraph("<b>(b) In 2016, Mericho village population was 2,800. In 2017 it increased by 8%. What was the population in 2017?</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Calculate the increase:", st))
    story.append(Paragraph("Increase = 8% of 2,800", st))
    story.append(Paragraph("= (8/100) x 2,800", st))
    story.append(Paragraph("= 0.08 x 2,800", st))
    story.append(Paragraph("= 224 people", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Add increase to original:", st))
    story.append(Paragraph("Population in 2017 = 2,800 + 224 = 3,024", st))
    story.append(S(4))
    story.append(ans("Final Answer: Population in 2017 = 3,024"))
    story.append(S(6))
    story.append(tip("A shortcut for percentage increase: multiply by (100% + increase%). So 2,800 x 1.08 = 3,024. This works because 108% = 100% (original) + 8% (increase)."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Comparing fractions, LCD, percentage increase. Study tip: To compare fractions, always convert to the same denominator first."))
    story.append(PageBreak())

    # ===== Q3: Units and Profit =====
    story.append(qheader(3, "Unit Conversion and Profit", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) 1,000 tonnes of maize shared among 25 schools. How many kilograms each?</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Convert tonnes to kilograms.", st))
    story.append(Paragraph("1 tonne = 1,000 kg", st))
    story.append(Paragraph("1,000 tonnes = 1,000 x 1,000 = 1,000,000 kg", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Divide equally among 25 schools:", st))
    story.append(Paragraph("Each school = 1,000,000 / 25 = 40,000 kg", st))
    story.append(S(4))
    story.append(ans("Final Answer: Each school gets 40,000 kg"))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Radio bought for Tsh. 80,000 and sold at 20% profit. Find profit and selling price.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Calculate the profit:", st))
    story.append(Paragraph("Profit = 20% of Cost Price", st))
    story.append(Paragraph("= (20/100) x 80,000", st))
    story.append(Paragraph("= 0.20 x 80,000", st))
    story.append(Paragraph("= Tsh. 16,000", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Calculate selling price:", st))
    story.append(Paragraph("Selling Price = Cost Price + Profit", st))
    story.append(Paragraph("= 80,000 + 16,000 = Tsh. 96,000", st))
    story.append(S(4))
    story.append(ans("Final Answer: Profit = Tsh. 16,000. Selling Price = Tsh. 96,000"))
    story.append(S(6))
    story.append(warn("Profit percentage is ALWAYS calculated based on the COST PRICE (buying price), not the selling price. A common exam mistake is calculating 20% of the selling price instead."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Unit conversion (tonnes to kg), profit and selling price. Study tip: Selling Price = Cost Price + Profit. Loss = Cost Price - Selling Price."))
    story.append(PageBreak())

    # ===== Q4: Trapezium Angles and Area =====
    story.append(qheader(4, "Trapezium Angles and Square Area", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) ABCD is a trapezium with AD parallel to BC. Angle A = 60 degrees, Angle D = 40 degrees. Find angles a, b, and c.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("In a trapezium, one pair of opposite sides is parallel. The arrows show AD is parallel to BC.", body))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Since AD is parallel to BC, we can use co-interior angles (also called same-side interior angles or allied angles).", st))
    story.append(Paragraph("Co-interior angles add up to 180 degrees.", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Find angle b (at vertex B):", st))
    story.append(Paragraph("Angle A and angle B are co-interior angles (between parallel lines AD and BC, with AB as transversal).", st))
    story.append(Paragraph("Angle A + angle b = 180 degrees", st))
    story.append(Paragraph("60 + b = 180", st))
    story.append(Paragraph("b = 120 degrees", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Find angle c (interior angle at C):", st))
    story.append(Paragraph("Angle D and angle C are co-interior angles.", st))
    story.append(Paragraph("40 + c = 180", st))
    story.append(Paragraph("c = 140 degrees", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 4:</b> Find angle a (exterior angle at C on the extended line):", st))
    story.append(Paragraph("Angles on a straight line add up to 180 degrees.", st))
    story.append(Paragraph("a + c = 180", st))
    story.append(Paragraph("a = 180 - 140 = 40 degrees", st))
    story.append(S(4))
    story.append(ans("Final Answer: a = 40 degrees, b = 120 degrees, c = 140 degrees"))
    story.append(S(6))
    story.append(Paragraph("Quick check: Sum of interior angles = 60 + 120 + 140 + 40 = 360 degrees. Correct! (A quadrilateral always has 360 degrees total.)", st))
    story.append(S(6))
    story.append(tip("Co-interior angles (between parallel lines on the same side of a transversal) always add up to 180 degrees. Alternate angles are equal. Corresponding angles are equal."))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Square room floor, side = 5 metres. Find perimeter and area.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Perimeter:</b>", sub))
    story.append(Paragraph("The perimeter is the total distance around the outside.", st))
    story.append(Paragraph("Perimeter of a square = 4 x side = 4 x 5 = 20 m", st))
    story.append(S(4))
    story.append(Paragraph("<b>Area:</b>", sub))
    story.append(Paragraph("The area is the space inside the shape.", st))
    story.append(Paragraph("Area of a square = side x side = 5 x 5 = 25 m<super>2</super>", st))
    story.append(S(4))
    story.append(ans("Final Answer: Perimeter = 20 m, Area = 25 m<super>2</super>"))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Trapezium angles, co-interior angles, perimeter and area of a square. Study tip: Interior angles of any quadrilateral always add up to 360 degrees."))
    story.append(PageBreak())

    # ===== Q5: Linear and Quadratic Equations =====
    story.append(qheader(5, "Linear Equation and Completing the Square", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) If (6y + 1)/4 = 5(y + 5)/6, find y correct to three significant figures.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Cross multiply to remove the fractions:", st))
    story.append(Paragraph("6 x (6y + 1) = 4 x 5(y + 5)", st))
    story.append(Paragraph("6(6y + 1) = 20(y + 5)", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Expand both sides:", st))
    story.append(Paragraph("36y + 6 = 20y + 100", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Collect like terms:", st))
    story.append(Paragraph("36y - 20y = 100 - 6", st))
    story.append(Paragraph("16y = 94", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 4:</b> Divide both sides by 16:", st))
    story.append(Paragraph("y = 94/16 = 5.875", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 5:</b> Round to 3 significant figures:", st))
    story.append(Paragraph("5.875 has 4 significant figures. To 3 sig fig: 5.88 (the 7 rounds up the second 7...)", st))
    story.append(Paragraph("5.875 to 3 sig fig = 5.88", st))
    story.append(S(4))
    story.append(ans("Final Answer: y = 5.88 (to 3 significant figures)"))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Solve 3x<super>2</super> - 7x - 6 = 0 by completing the square.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Divide everything by 3 (the number in front of x<super>2</super>):", st))
    story.append(Paragraph("x<super>2</super> - (7/3)x - 2 = 0", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Move the constant to the right side:", st))
    story.append(Paragraph("x<super>2</super> - (7/3)x = 2", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> To complete the square, take half of the coefficient of x, then square it:", st))
    story.append(Paragraph("Half of -7/3 = -7/6", st))
    story.append(Paragraph("(-7/6)<super>2</super> = 49/36", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 4:</b> Add 49/36 to both sides:", st))
    story.append(Paragraph("x<super>2</super> - (7/3)x + 49/36 = 2 + 49/36", st))
    story.append(Paragraph("(x - 7/6)<super>2</super> = 72/36 + 49/36 = 121/36", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 5:</b> Take square root of both sides:", st))
    story.append(Paragraph("x - 7/6 = +/- 11/6", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 6:</b> Solve for x:", st))
    story.append(Paragraph("x = 7/6 + 11/6 = 18/6 = 3", st))
    story.append(Paragraph("OR x = 7/6 - 11/6 = -4/6 = -2/3", st))
    story.append(S(4))
    story.append(ans("Final Answer: x = 3 or x = -2/3"))
    story.append(S(6))
    story.append(warn("When completing the square for ax<super>2</super> + bx + c = 0, you MUST divide by 'a' first if a is not 1. Many students forget this step and get wrong answers."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Linear equations with fractions, completing the square. Study tip: Steps for completing the square: (1) Make coefficient of x<super>2</super> = 1, (2) Move constant, (3) Add (b/2)<super>2</super> to both sides, (4) Factor and solve."))
    story.append(PageBreak())

    # ===== Q6: Gradient and Reflection =====
    story.append(qheader(6, "Gradient and Reflection", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) Find the gradient of the line joining (-1, 2) and (3, -5).</b>", sub))
    story.append(S(4))
    story.append(Paragraph("The gradient (slope) tells us how steep a line is. It measures how much the line goes up or down for every step to the right.", body))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Use the gradient formula:", st))
    story.append(Paragraph("Gradient = (y<sub>2</sub> - y<sub>1</sub>) / (x<sub>2</sub> - x<sub>1</sub>)", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Label the points: (-1, 2) is (x<sub>1</sub>, y<sub>1</sub>) and (3, -5) is (x<sub>2</sub>, y<sub>2</sub>).", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Substitute:", st))
    story.append(Paragraph("Gradient = (-5 - 2) / (3 - (-1)) = -7 / 4", st))
    story.append(S(4))
    story.append(ans("Final Answer: Gradient = -7/4"))
    story.append(S(4))
    story.append(Paragraph("The negative sign means the line slopes downward from left to right.", st))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Find the image of P(-3, 7) after reflection in the x-axis and y-axis.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Reflection in the x-axis:</b>", sub))
    story.append(Paragraph("When we reflect in the x-axis, the x-coordinate stays the same but the y-coordinate changes sign (positive becomes negative, negative becomes positive).", st))
    story.append(Paragraph("Rule: (x, y) becomes (x, -y)", st))
    story.append(Paragraph("P(-3, 7) becomes P'(-3, -7)", st))
    story.append(S(4))
    story.append(ans("Reflection in x-axis: P' = (-3, -7)"))
    story.append(S(6))
    story.append(Paragraph("<b>Reflection in the y-axis:</b>", sub))
    story.append(Paragraph("When we reflect in the y-axis, the y-coordinate stays the same but the x-coordinate changes sign.", st))
    story.append(Paragraph("Rule: (x, y) becomes (-x, y)", st))
    story.append(Paragraph("P(-3, 7) becomes P''(3, 7)", st))
    story.append(S(4))
    story.append(ans("Reflection in y-axis: P'' = (3, 7)"))
    story.append(S(6))
    story.append(tip("Easy way to remember: x-axis reflection flips the Y value. y-axis reflection flips the X value. Think: reflecting in x affects y, reflecting in y affects x."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Gradient formula, reflections. Study tip: A positive gradient slopes upward (left to right). A negative gradient slopes downward."))
    story.append(PageBreak())

    # ===== Q7: Exponents and Logarithms =====
    story.append(qheader(7, "Exponents and Logarithms", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) Solve for n: 16<super>(1-n)</super> x 2<super>(1+n)</super> = 1/2</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Express everything as powers of 2:", st))
    story.append(Paragraph("16 = 2<super>4</super>, so 16<super>(1-n)</super> = (2<super>4</super>)<super>(1-n)</super> = 2<super>4(1-n)</super> = 2<super>(4-4n)</super>", st))
    story.append(Paragraph("1/2 = 2<super>-1</super>", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Rewrite the equation:", st))
    story.append(Paragraph("2<super>(4-4n)</super> x 2<super>(1+n)</super> = 2<super>-1</super>", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> When multiplying powers with the same base, add the exponents:", st))
    story.append(Paragraph("2<super>(4-4n+1+n)</super> = 2<super>-1</super>", st))
    story.append(Paragraph("2<super>(5-3n)</super> = 2<super>-1</super>", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 4:</b> Since the bases are equal, the exponents must be equal:", st))
    story.append(Paragraph("5 - 3n = -1", st))
    story.append(Paragraph("5 + 1 = 3n", st))
    story.append(Paragraph("6 = 3n", st))
    story.append(Paragraph("n = 2", st))
    story.append(S(4))
    story.append(ans("Final Answer: n = 2"))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Find x: log(2x<super>2</super> + 1) + log 4 = log(7x<super>2</super> + 8)</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Use the log rule: log A + log B = log(A x B):", st))
    story.append(Paragraph("log[4(2x<super>2</super> + 1)] = log(7x<super>2</super> + 8)", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> If log A = log B, then A = B:", st))
    story.append(Paragraph("4(2x<super>2</super> + 1) = 7x<super>2</super> + 8", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Expand and simplify:", st))
    story.append(Paragraph("8x<super>2</super> + 4 = 7x<super>2</super> + 8", st))
    story.append(Paragraph("8x<super>2</super> - 7x<super>2</super> = 8 - 4", st))
    story.append(Paragraph("x<super>2</super> = 4", st))
    story.append(Paragraph("x = +/- 2", st))
    story.append(S(4))
    story.append(ans("Final Answer: x = 2 or x = -2"))
    story.append(S(6))
    story.append(tip("Key log rules: log A + log B = log(AB). log A - log B = log(A/B). n log A = log(A<super>n</super>). If log A = log B, then A = B."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Laws of exponents, logarithm properties. Study tip: Express all terms as powers of the same base when solving exponential equations."))
    story.append(PageBreak())

    # ===== Q8: Similar Triangles and Congruence =====
    story.append(qheader(8, "Similar Triangles and Congruence Proof", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) In the figure, AD:BD = 3/5 and AC = 9.6 cm. DE is parallel to BC. Find AE.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("When a line is drawn parallel to one side of a triangle and cuts the other two sides, it divides those sides in the same ratio. This is called the Basic Proportionality Theorem (or Intercept Theorem).", body))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Since DE is parallel to BC, by the Basic Proportionality Theorem:", st))
    story.append(Paragraph("AD/AB = AE/AC", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Find AD/AB:", st))
    story.append(Paragraph("AD:BD = 3:5", st))
    story.append(Paragraph("So AB = AD + BD. If AD = 3 parts, BD = 5 parts, then AB = 3 + 5 = 8 parts.", st))
    story.append(Paragraph("AD/AB = 3/8", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Substitute into the proportion:", st))
    story.append(Paragraph("AE/9.6 = 3/8", st))
    story.append(Paragraph("AE = 9.6 x 3/8", st))
    story.append(Paragraph("AE = 28.8/8", st))
    story.append(Paragraph("AE = 3.6 cm", st))
    story.append(S(4))
    story.append(ans("Final Answer: AE = 3.6 cm"))
    story.append(S(8))

    story.append(Paragraph("<b>(b) ABC is a triangle where AB = AC and D is the midpoint of BC. Prove that angle ABD = angle ACD.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Proof:</b>", sub))
    story.append(Paragraph("In triangles ABD and ACD:", st))
    story.append(Paragraph("1. AB = AC (given - this is an isosceles triangle)", st))
    story.append(Paragraph("2. BD = DC (given - D is the midpoint of BC, so it splits BC into two equal halves)", st))
    story.append(Paragraph("3. AD = AD (common side - both triangles share this side)", st))
    story.append(S(2))
    story.append(Paragraph("Therefore, Triangle ABD is congruent to Triangle ACD by SSS (Side-Side-Side) congruence condition.", st))
    story.append(S(2))
    story.append(Paragraph("Since the triangles are congruent, all their corresponding parts are equal.", st))
    story.append(Paragraph("Therefore, angle ABD = angle ACD (corresponding angles of congruent triangles).", st))
    story.append(S(4))
    story.append(ans("Proved: Angle ABD = Angle ACD (by SSS congruence)"))
    story.append(S(6))
    story.append(tip("The conditions for triangle congruence are: SSS (3 sides), SAS (2 sides and included angle), ASA (2 angles and included side), AAS (2 angles and non-included side), RHS (right angle, hypotenuse, side)."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Basic Proportionality Theorem, congruent triangle proofs. Study tip: When DE is parallel to BC in triangle ABC, then AD/AB = AE/AC = DE/BC."))
    story.append(PageBreak())

    # ===== Q9: Trigonometry and Pythagoras =====
    story.append(qheader(9, "Angle of Elevation and Pythagoras", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) Angle of elevation of top of building is 25 degrees. The point is 80 m from base. Find the height.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("The angle of elevation is the angle you look UP from the horizontal (ground level) to see the top of something.", body))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Draw a right triangle. The building is the vertical side (opposite), the ground distance is the horizontal side (adjacent), and 25 degrees is the angle at the ground.", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Use the tangent ratio (we have adjacent and want opposite):", st))
    story.append(Paragraph("tan(angle) = opposite / adjacent", st))
    story.append(Paragraph("tan(25 degrees) = height / 80", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Look up tan(25 degrees) in your math tables:", st))
    story.append(Paragraph("tan(25 degrees) = 0.4663", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 4:</b> Solve for height:", st))
    story.append(Paragraph("height = 80 x 0.4663 = 37.304", st))
    story.append(Paragraph("Round to 1 decimal place: 37.3 m", st))
    story.append(S(4))
    story.append(ans("Final Answer: Height of building = 37.3 m"))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Right triangle with BA = 6 m, AC = 8 m, angle A = 90 degrees. Find BC.</b>", sub))
    story.append(S(4))
    story.append(Paragraph("Since angle A = 90 degrees, BC is the hypotenuse (the longest side, opposite the right angle).", body))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Use the Pythagoras Theorem:", st))
    story.append(Paragraph("The formula is: hypotenuse<super>2</super> = side 1<super>2</super> + side 2<super>2</super>", st))
    story.append(Paragraph("BC<super>2</super> = BA<super>2</super> + AC<super>2</super>", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Substitute the values:", st))
    story.append(Paragraph("BC<super>2</super> = 6<super>2</super> + 8<super>2</super>", st))
    story.append(Paragraph("BC<super>2</super> = 36 + 64", st))
    story.append(Paragraph("BC<super>2</super> = 100", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 3:</b> Take the square root:", st))
    story.append(Paragraph("BC = sqrt(100) = 10 m", st))
    story.append(S(4))
    story.append(ans("Final Answer: BC = 10 m"))
    story.append(S(6))
    story.append(tip("The 3-4-5 right triangle is very common in exams! 6-8-10 is just 3-4-5 multiplied by 2. Other common Pythagorean triples: 5-12-13, 8-15-17, 7-24-25."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Angle of elevation, trigonometric ratios, Pythagoras theorem. Study tip: SOH-CAH-TOA: Sin = Opposite/Hypotenuse, Cos = Adjacent/Hypotenuse, Tan = Opposite/Adjacent."))
    story.append(PageBreak())

    # ===== Q10: Sets and Pie Charts =====
    story.append(qheader(10, "Sets and Pie Charts", styles))
    story.append(S(8))
    story.append(Paragraph("<b>(a) 250 students attended day 1, 350 on day 2, 150 on both days, 10 absent both days. How many students total? (No Venn diagram)</b>", sub))
    story.append(S(4))
    story.append(Paragraph("<b>Step 1:</b> Use the addition formula for sets:", st))
    story.append(Paragraph("n(Day 1 or Day 2) = n(Day 1) + n(Day 2) - n(Both days)", st))
    story.append(Paragraph("= 250 + 350 - 150", st))
    story.append(Paragraph("= 450 students attended at least one day", st))
    story.append(S(2))
    story.append(Paragraph("<b>Step 2:</b> Add those who were absent both days:", st))
    story.append(Paragraph("Total students = 450 + 10 = 460", st))
    story.append(S(4))
    story.append(ans("Final Answer: The school has 460 students"))
    story.append(S(6))
    story.append(warn("Do not just add 250 + 350! That counts the 150 students who came both days TWICE. You must subtract the overlap: 250 + 350 - 150 = 450."))
    story.append(S(8))

    story.append(Paragraph("<b>(b) Pie chart: Kiswahili = 210 degrees, Mathematics = 120 degrees, Chemistry = 30 degrees.</b>", sub))
    story.append(S(4))

    story.append(Paragraph("<b>(i) Fraction of students who passed Kiswahili:</b>", sub))
    story.append(Paragraph("A full circle = 360 degrees.", st))
    story.append(Paragraph("Fraction = Kiswahili angle / Total angle = 210/360", st))
    story.append(Paragraph("Simplify: divide both by 30: 210/360 = 7/12", st))
    story.append(S(4))
    story.append(ans("Answer: 7/12 of students passed Kiswahili"))
    story.append(S(6))

    story.append(Paragraph("<b>(ii) Percentage who passed Mathematics:</b>", sub))
    story.append(Paragraph("Percentage = (Mathematics angle / 360) x 100%", st))
    story.append(Paragraph("= (120/360) x 100%", st))
    story.append(Paragraph("= (1/3) x 100%", st))
    story.append(Paragraph("= 33.33% (or 33 and 1/3 %)", st))
    story.append(S(4))
    story.append(ans("Answer: 33.33% (or 33 1/3 %) passed Mathematics"))
    story.append(S(6))

    story.append(Paragraph("<b>(iii) Percentage who passed Mathematics and Chemistry:</b>", sub))
    story.append(Paragraph("Combined angle = 120 + 30 = 150 degrees", st))
    story.append(Paragraph("Percentage = (150/360) x 100%", st))
    story.append(Paragraph("= (5/12) x 100%", st))
    story.append(Paragraph("= 41.67% (or 41 and 2/3 %)", st))
    story.append(S(4))
    story.append(ans("Answer: 41.67% (or 41 2/3 %) passed Mathematics and Chemistry"))
    story.append(S(6))
    story.append(tip("In a pie chart, the whole circle = 360 degrees = 100%. To convert angle to percentage: (angle/360) x 100. To convert angle to fraction: angle/360 then simplify."))
    story.append(S(6))
    story.append(summary("Total marks: 10. Key topics: Sets, addition formula, pie charts, fractions and percentages. Study tip: Always check that pie chart angles add up to 360 degrees (210 + 120 + 30 = 360 here)."))
    story.append(PageBreak())

    # ========== CLOSING ==========
    story.append(S(120))
    story.append(Paragraph("myTZStudies", styles['ClosingTitle']))
    story.append(S(6))
    story.append(Paragraph("Your Free Tanzanian Exam Library", styles['CoverSubtitle']))
    story.append(S(30))
    story.append(Paragraph("This answer key was created by myTZStudies<br/>to help Tanzanian students study smarter.", styles['ClosingText']))
    story.append(S(15))
    story.append(Paragraph("Find more past papers and answer keys at:", styles['ClosingText']))
    story.append(S(6))
    story.append(Paragraph("mytzstudies.com", styles['CoverURL']))
    story.append(S(30))
    story.append(Paragraph("Past Exam Papers | Answer Keys | Free Access<br/>Standard 4 to Form 6 | All Subjects Covered", styles['ClosingText']))
    story.append(S(20))
    story.append(Paragraph("Share this with a friend.<br/>Every student deserves free study materials.", styles['CoverShare']))

    doc.build(story, onFirstPage=footer_func, onLaterPages=footer_func)
    print(f"PDF created at: {OUTPUT_PATH}")


if __name__ == "__main__":
    build_pdf()
