"""add comment model

Revision ID: de8eb5308645
Revises: 0b594a9c63bf
Create Date: 2026-03-25 10:42:29.778739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8eb5308645'
down_revision = '0b594a9c63bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('paper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pw_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.alter_column('pw_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('event',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('paper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
